// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Actor.proto

package com.myflix.adapter.grpc.protofiles.actor;

public final class ActorProto {
  private ActorProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Actor_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Actor_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Character_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Character_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_saveRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_saveRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_saveResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_saveResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_deleteRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_deleteRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_deleteResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_deleteResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_getAllRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_getAllRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_getAllResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_getAllResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_getRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_getRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_getResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_getResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_doCharacterRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_doCharacterRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_doCharacterResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_doCharacterResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_getCharactersRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_getCharactersRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_getCharactersResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_getCharactersResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013Actor.proto\"9\n\005Actor\022\017\n\007idActor\030\001 \001(\t\022" +
      "\014\n\004name\030\002 \001(\t\022\021\n\tbirthDate\030\003 \001(\003\";\n\tChar" +
      "acter\022\017\n\007idMovie\030\001 \001(\t\022\017\n\007idActor\030\002 \001(\t\022" +
      "\014\n\004name\030\003 \001(\t\".\n\013saveRequest\022\014\n\004name\030\001 \001" +
      "(\t\022\021\n\tbirthDate\030\002 \001(\003\"%\n\014saveResponse\022\025\n" +
      "\005actor\030\001 \001(\0132\006.Actor\" \n\rdeleteRequest\022\017\n" +
      "\007idActor\030\001 \001(\t\"\020\n\016deleteResponse\"\017\n\rgetA" +
      "llRequest\"\'\n\016getAllResponse\022\025\n\005actor\030\001 \001" +
      "(\0132\006.Actor\"\035\n\ngetRequest\022\017\n\007idActor\030\001 \001(" +
      "\t\"$\n\013getResponse\022\025\n\005actor\030\001 \001(\0132\006.Actor\"" +
      "D\n\022doCharacterRequest\022\017\n\007idActor\030\001 \001(\t\022\017" +
      "\n\007movieId\030\002 \001(\t\022\014\n\004name\030\003 \001(\t\"\025\n\023doChara" +
      "cterResponse\"\'\n\024getCharactersRequest\022\017\n\007" +
      "idActor\030\001 \001(\t\"6\n\025getCharactersResponse\022\035" +
      "\n\tcharacter\030\001 \001(\0132\n.Character2\267\002\n\014ActorS" +
      "ervice\022%\n\004save\022\014.saveRequest\032\r.saveRespo" +
      "nse\"\000\022+\n\006delete\022\016.deleteRequest\032\017.delete" +
      "Response\"\000\022-\n\006getAll\022\016.getAllRequest\032\017.g" +
      "etAllResponse\"\0000\001\022$\n\003get\022\013.getRequest\032\014." +
      "getResponse\"\0000\001\022:\n\013doCharacter\022\023.doChara" +
      "cterRequest\032\024.doCharacterResponse\"\000\022B\n\rg" +
      "etCharacters\022\025.getCharactersRequest\032\026.ge" +
      "tCharactersResponse\"\0000\001B8\n(com.myflix.ad" +
      "apter.grpc.protofiles.actorB\nActorProtoP" +
      "\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Actor_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Actor_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Actor_descriptor,
        new java.lang.String[] { "IdActor", "Name", "BirthDate", });
    internal_static_Character_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Character_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Character_descriptor,
        new java.lang.String[] { "IdMovie", "IdActor", "Name", });
    internal_static_saveRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_saveRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_saveRequest_descriptor,
        new java.lang.String[] { "Name", "BirthDate", });
    internal_static_saveResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_saveResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_saveResponse_descriptor,
        new java.lang.String[] { "Actor", });
    internal_static_deleteRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_deleteRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_deleteRequest_descriptor,
        new java.lang.String[] { "IdActor", });
    internal_static_deleteResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_deleteResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_deleteResponse_descriptor,
        new java.lang.String[] { });
    internal_static_getAllRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_getAllRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_getAllRequest_descriptor,
        new java.lang.String[] { });
    internal_static_getAllResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_getAllResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_getAllResponse_descriptor,
        new java.lang.String[] { "Actor", });
    internal_static_getRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_getRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_getRequest_descriptor,
        new java.lang.String[] { "IdActor", });
    internal_static_getResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_getResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_getResponse_descriptor,
        new java.lang.String[] { "Actor", });
    internal_static_doCharacterRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_doCharacterRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_doCharacterRequest_descriptor,
        new java.lang.String[] { "IdActor", "MovieId", "Name", });
    internal_static_doCharacterResponse_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_doCharacterResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_doCharacterResponse_descriptor,
        new java.lang.String[] { });
    internal_static_getCharactersRequest_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_getCharactersRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_getCharactersRequest_descriptor,
        new java.lang.String[] { "IdActor", });
    internal_static_getCharactersResponse_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_getCharactersResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_getCharactersResponse_descriptor,
        new java.lang.String[] { "Character", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
