// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Actor.proto

package com.myflix.adapter.grpc.protofiles.actor;

public interface ActorOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Actor)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string idActor = 1;</code>
   */
  java.lang.String getIdActor();
  /**
   * <code>string idActor = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdActorBytes();

  /**
   * <code>string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int64 birthDate = 3;</code>
   */
  long getBirthDate();
}
