// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Actor.proto

package com.myflix.adapter.grpc.protofiles.actor;

/**
 * Protobuf type {@code Character}
 */
public  final class Character extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Character)
    CharacterOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Character.newBuilder() to construct.
  private Character(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Character() {
    idMovie_ = "";
    idActor_ = "";
    name_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Character(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            idMovie_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            idActor_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.myflix.adapter.grpc.protofiles.actor.ActorProto.internal_static_Character_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.myflix.adapter.grpc.protofiles.actor.ActorProto.internal_static_Character_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.myflix.adapter.grpc.protofiles.actor.Character.class, com.myflix.adapter.grpc.protofiles.actor.Character.Builder.class);
  }

  public static final int IDMOVIE_FIELD_NUMBER = 1;
  private volatile java.lang.Object idMovie_;
  /**
   * <code>string idMovie = 1;</code>
   */
  public java.lang.String getIdMovie() {
    java.lang.Object ref = idMovie_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      idMovie_ = s;
      return s;
    }
  }
  /**
   * <code>string idMovie = 1;</code>
   */
  public com.google.protobuf.ByteString
      getIdMovieBytes() {
    java.lang.Object ref = idMovie_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      idMovie_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int IDACTOR_FIELD_NUMBER = 2;
  private volatile java.lang.Object idActor_;
  /**
   * <code>string idActor = 2;</code>
   */
  public java.lang.String getIdActor() {
    java.lang.Object ref = idActor_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      idActor_ = s;
      return s;
    }
  }
  /**
   * <code>string idActor = 2;</code>
   */
  public com.google.protobuf.ByteString
      getIdActorBytes() {
    java.lang.Object ref = idActor_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      idActor_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NAME_FIELD_NUMBER = 3;
  private volatile java.lang.Object name_;
  /**
   * <code>string name = 3;</code>
   */
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 3;</code>
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getIdMovieBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, idMovie_);
    }
    if (!getIdActorBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, idActor_);
    }
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, name_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getIdMovieBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, idMovie_);
    }
    if (!getIdActorBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, idActor_);
    }
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, name_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.myflix.adapter.grpc.protofiles.actor.Character)) {
      return super.equals(obj);
    }
    com.myflix.adapter.grpc.protofiles.actor.Character other = (com.myflix.adapter.grpc.protofiles.actor.Character) obj;

    boolean result = true;
    result = result && getIdMovie()
        .equals(other.getIdMovie());
    result = result && getIdActor()
        .equals(other.getIdActor());
    result = result && getName()
        .equals(other.getName());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + IDMOVIE_FIELD_NUMBER;
    hash = (53 * hash) + getIdMovie().hashCode();
    hash = (37 * hash) + IDACTOR_FIELD_NUMBER;
    hash = (53 * hash) + getIdActor().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.myflix.adapter.grpc.protofiles.actor.Character parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.myflix.adapter.grpc.protofiles.actor.Character parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.myflix.adapter.grpc.protofiles.actor.Character parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.myflix.adapter.grpc.protofiles.actor.Character parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.myflix.adapter.grpc.protofiles.actor.Character parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.myflix.adapter.grpc.protofiles.actor.Character parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.myflix.adapter.grpc.protofiles.actor.Character parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.myflix.adapter.grpc.protofiles.actor.Character parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.myflix.adapter.grpc.protofiles.actor.Character parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.myflix.adapter.grpc.protofiles.actor.Character parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.myflix.adapter.grpc.protofiles.actor.Character parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.myflix.adapter.grpc.protofiles.actor.Character parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.myflix.adapter.grpc.protofiles.actor.Character prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Character}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Character)
      com.myflix.adapter.grpc.protofiles.actor.CharacterOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.myflix.adapter.grpc.protofiles.actor.ActorProto.internal_static_Character_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.myflix.adapter.grpc.protofiles.actor.ActorProto.internal_static_Character_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.myflix.adapter.grpc.protofiles.actor.Character.class, com.myflix.adapter.grpc.protofiles.actor.Character.Builder.class);
    }

    // Construct using com.myflix.adapter.grpc.protofiles.actor.Character.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      idMovie_ = "";

      idActor_ = "";

      name_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.myflix.adapter.grpc.protofiles.actor.ActorProto.internal_static_Character_descriptor;
    }

    @java.lang.Override
    public com.myflix.adapter.grpc.protofiles.actor.Character getDefaultInstanceForType() {
      return com.myflix.adapter.grpc.protofiles.actor.Character.getDefaultInstance();
    }

    @java.lang.Override
    public com.myflix.adapter.grpc.protofiles.actor.Character build() {
      com.myflix.adapter.grpc.protofiles.actor.Character result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.myflix.adapter.grpc.protofiles.actor.Character buildPartial() {
      com.myflix.adapter.grpc.protofiles.actor.Character result = new com.myflix.adapter.grpc.protofiles.actor.Character(this);
      result.idMovie_ = idMovie_;
      result.idActor_ = idActor_;
      result.name_ = name_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.myflix.adapter.grpc.protofiles.actor.Character) {
        return mergeFrom((com.myflix.adapter.grpc.protofiles.actor.Character)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.myflix.adapter.grpc.protofiles.actor.Character other) {
      if (other == com.myflix.adapter.grpc.protofiles.actor.Character.getDefaultInstance()) return this;
      if (!other.getIdMovie().isEmpty()) {
        idMovie_ = other.idMovie_;
        onChanged();
      }
      if (!other.getIdActor().isEmpty()) {
        idActor_ = other.idActor_;
        onChanged();
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.myflix.adapter.grpc.protofiles.actor.Character parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.myflix.adapter.grpc.protofiles.actor.Character) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object idMovie_ = "";
    /**
     * <code>string idMovie = 1;</code>
     */
    public java.lang.String getIdMovie() {
      java.lang.Object ref = idMovie_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        idMovie_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string idMovie = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdMovieBytes() {
      java.lang.Object ref = idMovie_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        idMovie_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string idMovie = 1;</code>
     */
    public Builder setIdMovie(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      idMovie_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string idMovie = 1;</code>
     */
    public Builder clearIdMovie() {
      
      idMovie_ = getDefaultInstance().getIdMovie();
      onChanged();
      return this;
    }
    /**
     * <code>string idMovie = 1;</code>
     */
    public Builder setIdMovieBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      idMovie_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object idActor_ = "";
    /**
     * <code>string idActor = 2;</code>
     */
    public java.lang.String getIdActor() {
      java.lang.Object ref = idActor_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        idActor_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string idActor = 2;</code>
     */
    public com.google.protobuf.ByteString
        getIdActorBytes() {
      java.lang.Object ref = idActor_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        idActor_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string idActor = 2;</code>
     */
    public Builder setIdActor(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      idActor_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string idActor = 2;</code>
     */
    public Builder clearIdActor() {
      
      idActor_ = getDefaultInstance().getIdActor();
      onChanged();
      return this;
    }
    /**
     * <code>string idActor = 2;</code>
     */
    public Builder setIdActorBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      idActor_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 3;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 3;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 3;</code>
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 3;</code>
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>string name = 3;</code>
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Character)
  }

  // @@protoc_insertion_point(class_scope:Character)
  private static final com.myflix.adapter.grpc.protofiles.actor.Character DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.myflix.adapter.grpc.protofiles.actor.Character();
  }

  public static com.myflix.adapter.grpc.protofiles.actor.Character getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Character>
      PARSER = new com.google.protobuf.AbstractParser<Character>() {
    @java.lang.Override
    public Character parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Character(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Character> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Character> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.myflix.adapter.grpc.protofiles.actor.Character getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

