// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Actor.proto

package com.myflix.adapter.grpc.protofiles.actor;

public interface doCharacterRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:doCharacterRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string idActor = 1;</code>
   */
  java.lang.String getIdActor();
  /**
   * <code>string idActor = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdActorBytes();

  /**
   * <code>string movieId = 2;</code>
   */
  java.lang.String getMovieId();
  /**
   * <code>string movieId = 2;</code>
   */
  com.google.protobuf.ByteString
      getMovieIdBytes();

  /**
   * <code>string name = 3;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 3;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
