// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Actor.proto

package com.myflix.adapter.grpc.protofiles.actor;

public interface getAllRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:getAllRequest)
    com.google.protobuf.MessageOrBuilder {
}
