// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Actor.proto

package com.myflix.adapter.grpc.protofiles.actor;

public interface getAllResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:getAllResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Actor actor = 1;</code>
   */
  boolean hasActor();
  /**
   * <code>.Actor actor = 1;</code>
   */
  com.myflix.adapter.grpc.protofiles.actor.Actor getActor();
  /**
   * <code>.Actor actor = 1;</code>
   */
  com.myflix.adapter.grpc.protofiles.actor.ActorOrBuilder getActorOrBuilder();
}
