// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Actor.proto

package com.myflix.adapter.grpc.protofiles.actor;

public interface getCharactersResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:getCharactersResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Character character = 1;</code>
   */
  boolean hasCharacter();
  /**
   * <code>.Character character = 1;</code>
   */
  com.myflix.adapter.grpc.protofiles.actor.Character getCharacter();
  /**
   * <code>.Character character = 1;</code>
   */
  com.myflix.adapter.grpc.protofiles.actor.CharacterOrBuilder getCharacterOrBuilder();
}
