// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Actor.proto

package com.myflix.adapter.grpc.protofiles.actor;

public interface getCharactersRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:getCharactersRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string idActor = 1;</code>
   */
  java.lang.String getIdActor();
  /**
   * <code>string idActor = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdActorBytes();
}
