// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Actor.proto

package com.myflix.adapter.grpc.protofiles.actor;

/**
 * Protobuf type {@code getCharactersResponse}
 */
public  final class getCharactersResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:getCharactersResponse)
    getCharactersResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use getCharactersResponse.newBuilder() to construct.
  private getCharactersResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private getCharactersResponse() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private getCharactersResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.myflix.adapter.grpc.protofiles.actor.Character.Builder subBuilder = null;
            if (character_ != null) {
              subBuilder = character_.toBuilder();
            }
            character_ = input.readMessage(com.myflix.adapter.grpc.protofiles.actor.Character.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(character_);
              character_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.myflix.adapter.grpc.protofiles.actor.ActorProto.internal_static_getCharactersResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.myflix.adapter.grpc.protofiles.actor.ActorProto.internal_static_getCharactersResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.myflix.adapter.grpc.protofiles.actor.getCharactersResponse.class, com.myflix.adapter.grpc.protofiles.actor.getCharactersResponse.Builder.class);
  }

  public static final int CHARACTER_FIELD_NUMBER = 1;
  private com.myflix.adapter.grpc.protofiles.actor.Character character_;
  /**
   * <code>.Character character = 1;</code>
   */
  public boolean hasCharacter() {
    return character_ != null;
  }
  /**
   * <code>.Character character = 1;</code>
   */
  public com.myflix.adapter.grpc.protofiles.actor.Character getCharacter() {
    return character_ == null ? com.myflix.adapter.grpc.protofiles.actor.Character.getDefaultInstance() : character_;
  }
  /**
   * <code>.Character character = 1;</code>
   */
  public com.myflix.adapter.grpc.protofiles.actor.CharacterOrBuilder getCharacterOrBuilder() {
    return getCharacter();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (character_ != null) {
      output.writeMessage(1, getCharacter());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (character_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getCharacter());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.myflix.adapter.grpc.protofiles.actor.getCharactersResponse)) {
      return super.equals(obj);
    }
    com.myflix.adapter.grpc.protofiles.actor.getCharactersResponse other = (com.myflix.adapter.grpc.protofiles.actor.getCharactersResponse) obj;

    boolean result = true;
    result = result && (hasCharacter() == other.hasCharacter());
    if (hasCharacter()) {
      result = result && getCharacter()
          .equals(other.getCharacter());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasCharacter()) {
      hash = (37 * hash) + CHARACTER_FIELD_NUMBER;
      hash = (53 * hash) + getCharacter().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.myflix.adapter.grpc.protofiles.actor.getCharactersResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.myflix.adapter.grpc.protofiles.actor.getCharactersResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.myflix.adapter.grpc.protofiles.actor.getCharactersResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.myflix.adapter.grpc.protofiles.actor.getCharactersResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.myflix.adapter.grpc.protofiles.actor.getCharactersResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.myflix.adapter.grpc.protofiles.actor.getCharactersResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.myflix.adapter.grpc.protofiles.actor.getCharactersResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.myflix.adapter.grpc.protofiles.actor.getCharactersResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.myflix.adapter.grpc.protofiles.actor.getCharactersResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.myflix.adapter.grpc.protofiles.actor.getCharactersResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.myflix.adapter.grpc.protofiles.actor.getCharactersResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.myflix.adapter.grpc.protofiles.actor.getCharactersResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.myflix.adapter.grpc.protofiles.actor.getCharactersResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code getCharactersResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:getCharactersResponse)
      com.myflix.adapter.grpc.protofiles.actor.getCharactersResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.myflix.adapter.grpc.protofiles.actor.ActorProto.internal_static_getCharactersResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.myflix.adapter.grpc.protofiles.actor.ActorProto.internal_static_getCharactersResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.myflix.adapter.grpc.protofiles.actor.getCharactersResponse.class, com.myflix.adapter.grpc.protofiles.actor.getCharactersResponse.Builder.class);
    }

    // Construct using com.myflix.adapter.grpc.protofiles.actor.getCharactersResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (characterBuilder_ == null) {
        character_ = null;
      } else {
        character_ = null;
        characterBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.myflix.adapter.grpc.protofiles.actor.ActorProto.internal_static_getCharactersResponse_descriptor;
    }

    @java.lang.Override
    public com.myflix.adapter.grpc.protofiles.actor.getCharactersResponse getDefaultInstanceForType() {
      return com.myflix.adapter.grpc.protofiles.actor.getCharactersResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.myflix.adapter.grpc.protofiles.actor.getCharactersResponse build() {
      com.myflix.adapter.grpc.protofiles.actor.getCharactersResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.myflix.adapter.grpc.protofiles.actor.getCharactersResponse buildPartial() {
      com.myflix.adapter.grpc.protofiles.actor.getCharactersResponse result = new com.myflix.adapter.grpc.protofiles.actor.getCharactersResponse(this);
      if (characterBuilder_ == null) {
        result.character_ = character_;
      } else {
        result.character_ = characterBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.myflix.adapter.grpc.protofiles.actor.getCharactersResponse) {
        return mergeFrom((com.myflix.adapter.grpc.protofiles.actor.getCharactersResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.myflix.adapter.grpc.protofiles.actor.getCharactersResponse other) {
      if (other == com.myflix.adapter.grpc.protofiles.actor.getCharactersResponse.getDefaultInstance()) return this;
      if (other.hasCharacter()) {
        mergeCharacter(other.getCharacter());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.myflix.adapter.grpc.protofiles.actor.getCharactersResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.myflix.adapter.grpc.protofiles.actor.getCharactersResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.myflix.adapter.grpc.protofiles.actor.Character character_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.myflix.adapter.grpc.protofiles.actor.Character, com.myflix.adapter.grpc.protofiles.actor.Character.Builder, com.myflix.adapter.grpc.protofiles.actor.CharacterOrBuilder> characterBuilder_;
    /**
     * <code>.Character character = 1;</code>
     */
    public boolean hasCharacter() {
      return characterBuilder_ != null || character_ != null;
    }
    /**
     * <code>.Character character = 1;</code>
     */
    public com.myflix.adapter.grpc.protofiles.actor.Character getCharacter() {
      if (characterBuilder_ == null) {
        return character_ == null ? com.myflix.adapter.grpc.protofiles.actor.Character.getDefaultInstance() : character_;
      } else {
        return characterBuilder_.getMessage();
      }
    }
    /**
     * <code>.Character character = 1;</code>
     */
    public Builder setCharacter(com.myflix.adapter.grpc.protofiles.actor.Character value) {
      if (characterBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        character_ = value;
        onChanged();
      } else {
        characterBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.Character character = 1;</code>
     */
    public Builder setCharacter(
        com.myflix.adapter.grpc.protofiles.actor.Character.Builder builderForValue) {
      if (characterBuilder_ == null) {
        character_ = builderForValue.build();
        onChanged();
      } else {
        characterBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.Character character = 1;</code>
     */
    public Builder mergeCharacter(com.myflix.adapter.grpc.protofiles.actor.Character value) {
      if (characterBuilder_ == null) {
        if (character_ != null) {
          character_ =
            com.myflix.adapter.grpc.protofiles.actor.Character.newBuilder(character_).mergeFrom(value).buildPartial();
        } else {
          character_ = value;
        }
        onChanged();
      } else {
        characterBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.Character character = 1;</code>
     */
    public Builder clearCharacter() {
      if (characterBuilder_ == null) {
        character_ = null;
        onChanged();
      } else {
        character_ = null;
        characterBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.Character character = 1;</code>
     */
    public com.myflix.adapter.grpc.protofiles.actor.Character.Builder getCharacterBuilder() {
      
      onChanged();
      return getCharacterFieldBuilder().getBuilder();
    }
    /**
     * <code>.Character character = 1;</code>
     */
    public com.myflix.adapter.grpc.protofiles.actor.CharacterOrBuilder getCharacterOrBuilder() {
      if (characterBuilder_ != null) {
        return characterBuilder_.getMessageOrBuilder();
      } else {
        return character_ == null ?
            com.myflix.adapter.grpc.protofiles.actor.Character.getDefaultInstance() : character_;
      }
    }
    /**
     * <code>.Character character = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.myflix.adapter.grpc.protofiles.actor.Character, com.myflix.adapter.grpc.protofiles.actor.Character.Builder, com.myflix.adapter.grpc.protofiles.actor.CharacterOrBuilder> 
        getCharacterFieldBuilder() {
      if (characterBuilder_ == null) {
        characterBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.myflix.adapter.grpc.protofiles.actor.Character, com.myflix.adapter.grpc.protofiles.actor.Character.Builder, com.myflix.adapter.grpc.protofiles.actor.CharacterOrBuilder>(
                getCharacter(),
                getParentForChildren(),
                isClean());
        character_ = null;
      }
      return characterBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:getCharactersResponse)
  }

  // @@protoc_insertion_point(class_scope:getCharactersResponse)
  private static final com.myflix.adapter.grpc.protofiles.actor.getCharactersResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.myflix.adapter.grpc.protofiles.actor.getCharactersResponse();
  }

  public static com.myflix.adapter.grpc.protofiles.actor.getCharactersResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<getCharactersResponse>
      PARSER = new com.google.protobuf.AbstractParser<getCharactersResponse>() {
    @java.lang.Override
    public getCharactersResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new getCharactersResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<getCharactersResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<getCharactersResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.myflix.adapter.grpc.protofiles.actor.getCharactersResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

