// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Customer.proto

package com.myflix.adapter.grpc.protofiles.customer;

public final class CustomerProto {
  private CustomerProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Customer_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Customer_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Watch_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Watch_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_saveRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_saveRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_saveResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_saveResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_deleteRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_deleteRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_deleteResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_deleteResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_getAllRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_getAllRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_getAllResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_getAllResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_getRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_getRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_getResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_getResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_watchRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_watchRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_watchResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_watchResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_getMoviesWatchedRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_getMoviesWatchedRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_getMoviesWatchedResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_getMoviesWatchedResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016Customer.proto\"?\n\010Customer\022\022\n\nidCustom" +
      "er\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\022\021\n\tbirthDate\030\003 \001(" +
      "\003\":\n\005Watch\022\022\n\nidCustomer\030\001 \001(\t\022\017\n\007idMovi" +
      "e\030\002 \001(\t\022\014\n\004date\030\003 \001(\003\".\n\013saveRequest\022\014\n\004" +
      "name\030\001 \001(\t\022\021\n\tbirthDate\030\002 \001(\003\"+\n\014saveRes" +
      "ponse\022\033\n\010customer\030\001 \001(\0132\t.Customer\"#\n\rde" +
      "leteRequest\022\022\n\nidCustomer\030\001 \001(\t\"\020\n\016delet" +
      "eResponse\"\017\n\rgetAllRequest\"-\n\016getAllResp" +
      "onse\022\033\n\010customer\030\001 \001(\0132\t.Customer\" \n\nget" +
      "Request\022\022\n\nidCustomer\030\001 \001(\t\"*\n\013getRespon" +
      "se\022\033\n\010customer\030\001 \001(\0132\t.Customer\"3\n\014watch" +
      "Request\022\022\n\nidCustomer\030\001 \001(\t\022\017\n\007idMovie\030\002" +
      " \001(\t\"\017\n\rwatchResponse\"-\n\027getMoviesWatche" +
      "dRequest\022\022\n\nidCustomer\030\001 \001(\t\"1\n\030getMovie" +
      "sWatchedResponse\022\025\n\005watch\030\001 \001(\0132\006.Watch2" +
      "\261\002\n\017CustomerService\022%\n\004save\022\014.saveReques" +
      "t\032\r.saveResponse\"\000\022+\n\006delete\022\016.deleteReq" +
      "uest\032\017.deleteResponse\"\000\022-\n\006getAll\022\016.getA" +
      "llRequest\032\017.getAllResponse\"\0000\001\022$\n\003get\022\013." +
      "getRequest\032\014.getResponse\"\0000\001\022(\n\005watch\022\r." +
      "watchRequest\032\016.watchResponse\"\000\022K\n\020getMov" +
      "iesWatched\022\030.getMoviesWatchedRequest\032\031.g" +
      "etMoviesWatchedResponse\"\0000\001B>\n+com.myfli" +
      "x.adapter.grpc.protofiles.customerB\rCust" +
      "omerProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Customer_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Customer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Customer_descriptor,
        new java.lang.String[] { "IdCustomer", "Name", "BirthDate", });
    internal_static_Watch_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Watch_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Watch_descriptor,
        new java.lang.String[] { "IdCustomer", "IdMovie", "Date", });
    internal_static_saveRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_saveRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_saveRequest_descriptor,
        new java.lang.String[] { "Name", "BirthDate", });
    internal_static_saveResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_saveResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_saveResponse_descriptor,
        new java.lang.String[] { "Customer", });
    internal_static_deleteRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_deleteRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_deleteRequest_descriptor,
        new java.lang.String[] { "IdCustomer", });
    internal_static_deleteResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_deleteResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_deleteResponse_descriptor,
        new java.lang.String[] { });
    internal_static_getAllRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_getAllRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_getAllRequest_descriptor,
        new java.lang.String[] { });
    internal_static_getAllResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_getAllResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_getAllResponse_descriptor,
        new java.lang.String[] { "Customer", });
    internal_static_getRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_getRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_getRequest_descriptor,
        new java.lang.String[] { "IdCustomer", });
    internal_static_getResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_getResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_getResponse_descriptor,
        new java.lang.String[] { "Customer", });
    internal_static_watchRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_watchRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_watchRequest_descriptor,
        new java.lang.String[] { "IdCustomer", "IdMovie", });
    internal_static_watchResponse_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_watchResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_watchResponse_descriptor,
        new java.lang.String[] { });
    internal_static_getMoviesWatchedRequest_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_getMoviesWatchedRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_getMoviesWatchedRequest_descriptor,
        new java.lang.String[] { "IdCustomer", });
    internal_static_getMoviesWatchedResponse_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_getMoviesWatchedResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_getMoviesWatchedResponse_descriptor,
        new java.lang.String[] { "Watch", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
