// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Customer.proto

package com.myflix.adapter.grpc.protofiles.customer;

public interface getAllRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:getAllRequest)
    com.google.protobuf.MessageOrBuilder {
}
