// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Customer.proto

package com.myflix.adapter.grpc.protofiles.customer;

public interface getMoviesWatchedResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:getMoviesWatchedResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Watch watch = 1;</code>
   */
  boolean hasWatch();
  /**
   * <code>.Watch watch = 1;</code>
   */
  com.myflix.adapter.grpc.protofiles.customer.Watch getWatch();
  /**
   * <code>.Watch watch = 1;</code>
   */
  com.myflix.adapter.grpc.protofiles.customer.WatchOrBuilder getWatchOrBuilder();
}
