// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Customer.proto

package com.myflix.adapter.grpc.protofiles.customer;

public interface getRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:getRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string idCustomer = 1;</code>
   */
  java.lang.String getIdCustomer();
  /**
   * <code>string idCustomer = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdCustomerBytes();
}
