// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Customer.proto

package com.myflix.adapter.grpc.protofiles.customer;

public interface saveRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:saveRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int64 birthDate = 2;</code>
   */
  long getBirthDate();
}
