// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Customer.proto

package com.myflix.adapter.grpc.protofiles.customer;

public interface saveResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:saveResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Customer customer = 1;</code>
   */
  boolean hasCustomer();
  /**
   * <code>.Customer customer = 1;</code>
   */
  com.myflix.adapter.grpc.protofiles.customer.Customer getCustomer();
  /**
   * <code>.Customer customer = 1;</code>
   */
  com.myflix.adapter.grpc.protofiles.customer.CustomerOrBuilder getCustomerOrBuilder();
}
