// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Customer.proto

package com.myflix.adapter.grpc.protofiles.customer;

public interface watchResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:watchResponse)
    com.google.protobuf.MessageOrBuilder {
}
