// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Movie.proto

package com.myflix.adapter.grpc.protofiles.movie;

public interface CharacterOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Character)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string idMovie = 1;</code>
   */
  java.lang.String getIdMovie();
  /**
   * <code>string idMovie = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdMovieBytes();

  /**
   * <code>string idActor = 2;</code>
   */
  java.lang.String getIdActor();
  /**
   * <code>string idActor = 2;</code>
   */
  com.google.protobuf.ByteString
      getIdActorBytes();

  /**
   * <code>string name = 3;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 3;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
