// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Movie.proto

package com.myflix.adapter.grpc.protofiles.movie;

public interface deleteResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:deleteResponse)
    com.google.protobuf.MessageOrBuilder {
}
