// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Movie.proto

package com.myflix.adapter.grpc.protofiles.movie;

public interface getCharactersResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:getCharactersResponse)
    com.google.protobuf.MessageOrBuilder {
}
