// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Movie.proto

package com.myflix.adapter.grpc.protofiles.movie;

public interface getCharactersRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:getCharactersRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string idMovie = 1;</code>
   */
  java.lang.String getIdMovie();
  /**
   * <code>string idMovie = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdMovieBytes();
}
