// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Movie.proto

package com.myflix.adapter.grpc.protofiles.movie;

public interface getMoviesWatchedResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:getMoviesWatchedResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Watch watch = 1;</code>
   */
  boolean hasWatch();
  /**
   * <code>.Watch watch = 1;</code>
   */
  com.myflix.adapter.grpc.protofiles.movie.Watch getWatch();
  /**
   * <code>.Watch watch = 1;</code>
   */
  com.myflix.adapter.grpc.protofiles.movie.WatchOrBuilder getWatchOrBuilder();
}
