// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Movie.proto

package com.myflix.adapter.grpc.protofiles.movie;

/**
 * Protobuf type {@code getMoviesWatchedResponse}
 */
public  final class getMoviesWatchedResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:getMoviesWatchedResponse)
    getMoviesWatchedResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use getMoviesWatchedResponse.newBuilder() to construct.
  private getMoviesWatchedResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private getMoviesWatchedResponse() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private getMoviesWatchedResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.myflix.adapter.grpc.protofiles.movie.Watch.Builder subBuilder = null;
            if (watch_ != null) {
              subBuilder = watch_.toBuilder();
            }
            watch_ = input.readMessage(com.myflix.adapter.grpc.protofiles.movie.Watch.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(watch_);
              watch_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.myflix.adapter.grpc.protofiles.movie.MovieProto.internal_static_getMoviesWatchedResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.myflix.adapter.grpc.protofiles.movie.MovieProto.internal_static_getMoviesWatchedResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.myflix.adapter.grpc.protofiles.movie.getMoviesWatchedResponse.class, com.myflix.adapter.grpc.protofiles.movie.getMoviesWatchedResponse.Builder.class);
  }

  public static final int WATCH_FIELD_NUMBER = 1;
  private com.myflix.adapter.grpc.protofiles.movie.Watch watch_;
  /**
   * <code>.Watch watch = 1;</code>
   */
  public boolean hasWatch() {
    return watch_ != null;
  }
  /**
   * <code>.Watch watch = 1;</code>
   */
  public com.myflix.adapter.grpc.protofiles.movie.Watch getWatch() {
    return watch_ == null ? com.myflix.adapter.grpc.protofiles.movie.Watch.getDefaultInstance() : watch_;
  }
  /**
   * <code>.Watch watch = 1;</code>
   */
  public com.myflix.adapter.grpc.protofiles.movie.WatchOrBuilder getWatchOrBuilder() {
    return getWatch();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (watch_ != null) {
      output.writeMessage(1, getWatch());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (watch_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getWatch());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.myflix.adapter.grpc.protofiles.movie.getMoviesWatchedResponse)) {
      return super.equals(obj);
    }
    com.myflix.adapter.grpc.protofiles.movie.getMoviesWatchedResponse other = (com.myflix.adapter.grpc.protofiles.movie.getMoviesWatchedResponse) obj;

    boolean result = true;
    result = result && (hasWatch() == other.hasWatch());
    if (hasWatch()) {
      result = result && getWatch()
          .equals(other.getWatch());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasWatch()) {
      hash = (37 * hash) + WATCH_FIELD_NUMBER;
      hash = (53 * hash) + getWatch().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.myflix.adapter.grpc.protofiles.movie.getMoviesWatchedResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.myflix.adapter.grpc.protofiles.movie.getMoviesWatchedResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.myflix.adapter.grpc.protofiles.movie.getMoviesWatchedResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.myflix.adapter.grpc.protofiles.movie.getMoviesWatchedResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.myflix.adapter.grpc.protofiles.movie.getMoviesWatchedResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.myflix.adapter.grpc.protofiles.movie.getMoviesWatchedResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.myflix.adapter.grpc.protofiles.movie.getMoviesWatchedResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.myflix.adapter.grpc.protofiles.movie.getMoviesWatchedResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.myflix.adapter.grpc.protofiles.movie.getMoviesWatchedResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.myflix.adapter.grpc.protofiles.movie.getMoviesWatchedResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.myflix.adapter.grpc.protofiles.movie.getMoviesWatchedResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.myflix.adapter.grpc.protofiles.movie.getMoviesWatchedResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.myflix.adapter.grpc.protofiles.movie.getMoviesWatchedResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code getMoviesWatchedResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:getMoviesWatchedResponse)
      com.myflix.adapter.grpc.protofiles.movie.getMoviesWatchedResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.myflix.adapter.grpc.protofiles.movie.MovieProto.internal_static_getMoviesWatchedResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.myflix.adapter.grpc.protofiles.movie.MovieProto.internal_static_getMoviesWatchedResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.myflix.adapter.grpc.protofiles.movie.getMoviesWatchedResponse.class, com.myflix.adapter.grpc.protofiles.movie.getMoviesWatchedResponse.Builder.class);
    }

    // Construct using com.myflix.adapter.grpc.protofiles.movie.getMoviesWatchedResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (watchBuilder_ == null) {
        watch_ = null;
      } else {
        watch_ = null;
        watchBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.myflix.adapter.grpc.protofiles.movie.MovieProto.internal_static_getMoviesWatchedResponse_descriptor;
    }

    @java.lang.Override
    public com.myflix.adapter.grpc.protofiles.movie.getMoviesWatchedResponse getDefaultInstanceForType() {
      return com.myflix.adapter.grpc.protofiles.movie.getMoviesWatchedResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.myflix.adapter.grpc.protofiles.movie.getMoviesWatchedResponse build() {
      com.myflix.adapter.grpc.protofiles.movie.getMoviesWatchedResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.myflix.adapter.grpc.protofiles.movie.getMoviesWatchedResponse buildPartial() {
      com.myflix.adapter.grpc.protofiles.movie.getMoviesWatchedResponse result = new com.myflix.adapter.grpc.protofiles.movie.getMoviesWatchedResponse(this);
      if (watchBuilder_ == null) {
        result.watch_ = watch_;
      } else {
        result.watch_ = watchBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.myflix.adapter.grpc.protofiles.movie.getMoviesWatchedResponse) {
        return mergeFrom((com.myflix.adapter.grpc.protofiles.movie.getMoviesWatchedResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.myflix.adapter.grpc.protofiles.movie.getMoviesWatchedResponse other) {
      if (other == com.myflix.adapter.grpc.protofiles.movie.getMoviesWatchedResponse.getDefaultInstance()) return this;
      if (other.hasWatch()) {
        mergeWatch(other.getWatch());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.myflix.adapter.grpc.protofiles.movie.getMoviesWatchedResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.myflix.adapter.grpc.protofiles.movie.getMoviesWatchedResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.myflix.adapter.grpc.protofiles.movie.Watch watch_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.myflix.adapter.grpc.protofiles.movie.Watch, com.myflix.adapter.grpc.protofiles.movie.Watch.Builder, com.myflix.adapter.grpc.protofiles.movie.WatchOrBuilder> watchBuilder_;
    /**
     * <code>.Watch watch = 1;</code>
     */
    public boolean hasWatch() {
      return watchBuilder_ != null || watch_ != null;
    }
    /**
     * <code>.Watch watch = 1;</code>
     */
    public com.myflix.adapter.grpc.protofiles.movie.Watch getWatch() {
      if (watchBuilder_ == null) {
        return watch_ == null ? com.myflix.adapter.grpc.protofiles.movie.Watch.getDefaultInstance() : watch_;
      } else {
        return watchBuilder_.getMessage();
      }
    }
    /**
     * <code>.Watch watch = 1;</code>
     */
    public Builder setWatch(com.myflix.adapter.grpc.protofiles.movie.Watch value) {
      if (watchBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        watch_ = value;
        onChanged();
      } else {
        watchBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.Watch watch = 1;</code>
     */
    public Builder setWatch(
        com.myflix.adapter.grpc.protofiles.movie.Watch.Builder builderForValue) {
      if (watchBuilder_ == null) {
        watch_ = builderForValue.build();
        onChanged();
      } else {
        watchBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.Watch watch = 1;</code>
     */
    public Builder mergeWatch(com.myflix.adapter.grpc.protofiles.movie.Watch value) {
      if (watchBuilder_ == null) {
        if (watch_ != null) {
          watch_ =
            com.myflix.adapter.grpc.protofiles.movie.Watch.newBuilder(watch_).mergeFrom(value).buildPartial();
        } else {
          watch_ = value;
        }
        onChanged();
      } else {
        watchBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.Watch watch = 1;</code>
     */
    public Builder clearWatch() {
      if (watchBuilder_ == null) {
        watch_ = null;
        onChanged();
      } else {
        watch_ = null;
        watchBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.Watch watch = 1;</code>
     */
    public com.myflix.adapter.grpc.protofiles.movie.Watch.Builder getWatchBuilder() {
      
      onChanged();
      return getWatchFieldBuilder().getBuilder();
    }
    /**
     * <code>.Watch watch = 1;</code>
     */
    public com.myflix.adapter.grpc.protofiles.movie.WatchOrBuilder getWatchOrBuilder() {
      if (watchBuilder_ != null) {
        return watchBuilder_.getMessageOrBuilder();
      } else {
        return watch_ == null ?
            com.myflix.adapter.grpc.protofiles.movie.Watch.getDefaultInstance() : watch_;
      }
    }
    /**
     * <code>.Watch watch = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.myflix.adapter.grpc.protofiles.movie.Watch, com.myflix.adapter.grpc.protofiles.movie.Watch.Builder, com.myflix.adapter.grpc.protofiles.movie.WatchOrBuilder> 
        getWatchFieldBuilder() {
      if (watchBuilder_ == null) {
        watchBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.myflix.adapter.grpc.protofiles.movie.Watch, com.myflix.adapter.grpc.protofiles.movie.Watch.Builder, com.myflix.adapter.grpc.protofiles.movie.WatchOrBuilder>(
                getWatch(),
                getParentForChildren(),
                isClean());
        watch_ = null;
      }
      return watchBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:getMoviesWatchedResponse)
  }

  // @@protoc_insertion_point(class_scope:getMoviesWatchedResponse)
  private static final com.myflix.adapter.grpc.protofiles.movie.getMoviesWatchedResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.myflix.adapter.grpc.protofiles.movie.getMoviesWatchedResponse();
  }

  public static com.myflix.adapter.grpc.protofiles.movie.getMoviesWatchedResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<getMoviesWatchedResponse>
      PARSER = new com.google.protobuf.AbstractParser<getMoviesWatchedResponse>() {
    @java.lang.Override
    public getMoviesWatchedResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new getMoviesWatchedResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<getMoviesWatchedResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<getMoviesWatchedResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.myflix.adapter.grpc.protofiles.movie.getMoviesWatchedResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

