// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Movie.proto

package com.myflix.adapter.grpc.protofiles.movie;

public interface getResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:getResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Movie movie = 1;</code>
   */
  boolean hasMovie();
  /**
   * <code>.Movie movie = 1;</code>
   */
  com.myflix.adapter.grpc.protofiles.movie.Movie getMovie();
  /**
   * <code>.Movie movie = 1;</code>
   */
  com.myflix.adapter.grpc.protofiles.movie.MovieOrBuilder getMovieOrBuilder();
}
