// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Movie.proto

package com.myflix.adapter.grpc.protofiles.movie;

public interface MovieOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Movie)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string idMovie = 1;</code>
   */
  java.lang.String getIdMovie();
  /**
   * <code>string idMovie = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdMovieBytes();

  /**
   * <code>string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 year = 3;</code>
   */
  int getYear();
}
