// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Movie.proto

package com.myflix.adapter.grpc.protofiles.movie;

public interface WatchOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Watch)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string idCustomer = 1;</code>
   */
  java.lang.String getIdCustomer();
  /**
   * <code>string idCustomer = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdCustomerBytes();

  /**
   * <code>string idMovie = 2;</code>
   */
  java.lang.String getIdMovie();
  /**
   * <code>string idMovie = 2;</code>
   */
  com.google.protobuf.ByteString
      getIdMovieBytes();

  /**
   * <code>int64 date = 3;</code>
   */
  long getDate();
}
